module.exports = [
  ['Saint-Bruno', 'QC', 'J3V J6J'],
  ['Lac-Saint-Charles', 'QC', 'G3G R1R'],
  ['Clermont', 'QC', 'G4A C8G'],
  ['L\'Assomption', 'QC', 'J5W L0C'],
  ['Donnacona', 'QC', 'G3M C6E'],
  ['Pointe-Claire', 'QC', 'H9R A0V'],
  ['Roberval', 'QC', 'G8H V7E'],
  ['Saint-Ambroise', 'QC', 'G7P R8A'],
  ['Duvernay', 'QC', 'H7E J1P'],
  ['Cap-Rouge', 'QC', 'G1Y E5H'],
  ['Masson-Angers', 'QC', 'J8M H6R'],
  ['Saint-Franþois', 'QC', 'H7B C2V'],
  ['Estrie-Est', 'QC', 'J0B T4M'],
  ['Saint-Colomban', 'QC', 'J5K B1T'],
  ['Hébertville', 'QC', 'G8N Y6J'],
  ['Saint-Henri', 'QC', 'H4C X6E'],
  ['Saint-Hippolyte', 'QC', 'J8A G4C'],
  ['Sainte-Marie', 'QC', 'G6E P3N'],
  ['Plessisville', 'QC', 'G6L H1T'],
  ['Val-d\'Or', 'QC', 'J9P E2N'],
  ['Saint-Émile', 'QC', 'G3E X4G'],
  ['Senneville', 'QC', 'H9K Y3Y'],
  ['Old Montreal', 'QC', 'H2Y B0J'],
  ['Kirkland', 'QC', 'H9J T2R'],
  ['Nunavik', 'QC', 'J0M S5H'],
  ['Coaticook', 'QC', 'J1A N9G'],
  ['Ville Émard', 'QC', 'H4E P3A'],
  ['Chelsea', 'QC', 'J9B B5H'],
  ['Saint-Sophie', 'QC', 'J5J G9B'],
  ['La Sarre', 'QC', 'J9Z G8M'],
  ['Duvernay-Est', 'QC', 'H7A A1S'],
  ['Îles-Laval', 'QC', 'H7Y H8N'],
  ['Appalaches', 'QC', 'G0R S3M'],
  ['Petite-Bourgogne', 'QC', 'H3J E5V'],
  ['Laurentides-Nord', 'QC', 'J0T H7A'],
  ['Magog', 'QC', 'J1X X4L'],
  ['Saint-Félicien', 'QC', 'G8K S9V'],
  ['Chaudière-Nord', 'QC', 'G0S N7Y'],
  ['Parc-Extension', 'QC', 'H3N A2Y'],
  ['Tour de la Bourse', 'QC', 'H4Z S9S'],
  ['Grand-Mère', 'QC', 'G9T X3P'],
  ['Varennes', 'QC', 'J3X L4R'],
  ['Dorval Outskirts', 'QC', 'H9P T5S'],
  ['Becancour', 'QC', 'G9H B3X'],
  ['Griffintown', 'QC', 'H3C T0X'],
  ['Laterrière', 'QC', 'G7N V6P'],
  ['Gaspésie-Ouest', 'QC', 'G0J X3R'],
  ['Marieville', 'QC', 'J3M T5K'],
  ['Louiseville', 'QC', 'J5V T9T'],
  ['Saint-Prime', 'QC', 'G8J V2G'],
  ['Outremont', 'QC', 'H2V N8B'],
  ['Lachute', 'QC', 'J8H A1X'],
  ['Rivière-du-Loup', 'QC', 'G5R T0A'],
  ['Beauharnois', 'QC', 'J6N J6X'],
  ['Black Lake', 'QC', 'G6H T2P'],
  ['Capitale-Nationale', 'QC', 'G0A N2S'],
  ['Hochelaga', 'QC', 'H1W H1K'],
  ['Fabreville', 'QC', 'H7P K0V'],
  ['Boucherville', 'QC', 'J4B B9G'],
  ['La Malbaie', 'QC', 'G5A A8N'],
  ['Bromont', 'QC', 'J2L K3P'],
  ['Mercier', 'QC', 'J6R B1G'],
  ['Place Desjardins', 'QC', 'H5B E2J'],
  ['Laval-des-Rapides', 'QC', 'H7N V3X'],
  ['Montérégie-Est', 'QC', 'J0J Y2S'],
  ['Asbestos', 'QC', 'J1T G1L'],
  ['Bois-Francs-Nord', 'QC', 'J0G H0P'],
  ['Montérégie-Nord', 'QC', 'J0L K5P'],
  ['Place Bonaventure', 'QC', 'H5A J3P'],
  ['Charny', 'QC', 'G6X T5R'],
  ['Pintendre', 'QC', 'G6C Y3B'],
  ['Beaconsfield', 'QC', 'H9W V3L'],
  ['Laval-sur-le-Lac', 'QC', 'H7R Y9P'],
  ['Reserved', 'QC', 'H0H V3L'],
  ['La Baie', 'QC', 'G7B G4J'],
  ['Saint-Constant', 'QC', 'J5A X2M'],
  ['Montmagny', 'QC', 'G5V A9N'],
  ['Amqui', 'QC', 'G5J H9M'],
  ['Nicolet', 'QC', 'J3T E0X'],
  ['Laurentides-Sud', 'QC', 'J0V J1M'],
  ['L\'Erable', 'QC', 'G0Y G1H'],
  ['Le Fjord', 'QC', 'G0T C1K'],
  ['Pont-Viau', 'QC', 'H7G X2P'],
  ['Lavaltrie', 'QC', 'J5T G8A'],
  ['Lanaudière-Nord', 'QC', 'J0K H0V'],
  ['Vimont', 'QC', 'H7M E7H'],
  ['Manicouagan', 'QC', 'G0H M4Y'],
  ['Saint-Luc', 'QC', 'J2W Y1S'],
  ['Greenfield Park', 'QC', 'J4V J8N'],
  ['Delson', 'QC', 'J5B L9X'],
  ['Sainte-Geneviève', 'QC', 'H9H A1V'],
  ['Joliette', 'QC', 'J6E S5J'],
  ['Chambly', 'QC', 'J3L R6P'],
  ['Gaspésie-Nord', 'QC', 'G0E P0V'],
  ['Thetford Mines', 'QC', 'G6G L9X'],
  ['Saint-Pierre', 'QC', 'H8R B8R'],
  ['Gaspé', 'QC', 'G4X C5E'],
  ['Buckingham', 'QC', 'J8L K1G'],
  ['Estrie-Ouest', 'QC', 'J0E V2A'],
  ['Gaspésie-Sud', 'QC', 'G0C L9P'],
  ['Pierrefonds', 'QC', 'H8Z A4V'],
  ['Mont-Laurier', 'QC', 'J9L A0G'],
  ['Maniwaki', 'QC', 'J9E E3E'],
  ['Outaouais-Sud', 'QC', 'J0X H3G'],
  ['Outaouais-Nord', 'QC', 'J0W T5E'],
  ['La Prairie', 'QC', 'J5R A3A'],
  ['Valleyfield', 'QC', 'J7X C4K'],
  ['Région de Beauce', 'QC', 'G0M E5H'],
  ['Chaudière-Sud', 'QC', 'G0N R9H'],
  ['Mauricie', 'QC', 'G0X N1P'],
  ['Sainte-Adèle', 'QC', 'J8B K0T'],
  ['Région d\'Oka', 'QC', 'J0N R7E'],
  ['Farnham', 'QC', 'J2N R5K'],
  ['Lanaudière-Sud', 'QC', 'J0R P0P'],
  ['Saint-Raymond', 'QC', 'G3L T0N'],
  ['Bois-Francs-Sud', 'QC', 'J0H K9Y'],
  ['Cap-aux-Meules', 'QC', 'G0B R4T'],
  ['Saint-Nicolas', 'QC', 'G7A X9V'],
  ['Chibougamau', 'QC', 'G8P V2B'],
  ['Mont-Tremblant', 'QC', 'J8E T7H'],
  ['Sainte-Julie', 'QC', 'J3E H3B'],
  ['Port-Cartier', 'QC', 'G5B K5P'],
  ['Windsor', 'QC', 'J1S E8A'],
  ['Cowansville', 'QC', 'J2K Y7Y'],
  ['Roxboro', 'QC', 'H8Y N0C'],
  ['Amos', 'QC', 'J9T E1M'],
  ['La Plaine', 'QC', 'J7M X9C'],
  ['Sainte-Rose', 'QC', 'H7L A5E'],
  ['L\'Île-Dorval', 'QC', 'H9S X3H'],
  ['Maisonneuve', 'QC', 'H1V X0B'],
  ['Albanel', 'QC', 'G8M B3J'],
  ['Matane', 'QC', 'G4W E9Y'],
  ['Mont-Joli', 'QC', 'G5H T9N'],
  ['L\'Épiphanie', 'QC', 'J5X R6B'],
  ['Pont-Rouge', 'QC', 'G3H M9M'],
  ['Lac-Megantic', 'QC', 'G6B A6S'],
  ['Hampstead', 'QC', 'H3X J5P'],
  ['Baie-Saint-Paul', 'QC', 'G3Z N5B'],
  ['L\'Île-Des-Soeurs', 'QC', 'H3E K1N'],
  ['Val-des-Monts', 'QC', 'J8N A6P'],
  ['Beauceville', 'QC', 'G5X J5G'],
  ['La Tuque', 'QC', 'G9X A7A'],
  ['Rock Forest', 'QC', 'J1N P9B'],
  ['Ville-Marie', 'QC', 'J9V T1G'],
  ['Chatham', 'QC', 'J8G K5J'],
  ['Sainte-Dorothée', 'QC', 'H7X B7K'],
  ['Degelis', 'QC', 'G5T L9X'],
  ['Gananoque', 'ON', 'K7G X7Y'],
  ['Kanata', 'ON', 'K2K H4T'],
  ['Orleans', 'ON', 'K1E X6G'],
  ['Aurora', 'ON', 'L4G J5T'],
  ['Hawkesbury', 'ON', 'K6A L9P'],
  ['Leamington', 'ON', 'N8H M8H'],
  ['York', 'ON', 'M6C A3V'],
  ['Ingersoll', 'ON', 'N5C R2C'],
  ['Brockville', 'ON', 'K6V R8H'],
  ['Lambton', 'ON', 'N0N N7B'],
  ['Fergus', 'ON', 'N1M M2L'],
  ['Arnprior', 'ON', 'K7S C9H'],
  ['Napanee', 'ON', 'K7R B2G'],
  ['Alliston', 'ON', 'L9R S1P'],
  ['Strathroy', 'ON', 'N7G R5M'],
  ['Kincardine', 'ON', 'N2Z R7C'],
  ['Oxford', 'ON', 'N0J E6V'],
  ['Hanover', 'ON', 'N4N G0H'],
  ['Tillsonburg', 'ON', 'N4G N4L'],
  ['Bradford', 'ON', 'L3Z Y0B'],
  ['Cumberland', 'ON', 'K4C H4R'],
  ['Ottawa', 'ON', 'K1G K8P'],
  ['Keswick', 'ON', 'L4P L8M'],
  ['Baden', 'ON', 'N3A S7R'],
  ['Wellington', 'ON', 'N0B G1H'],
  ['Manitoulin', 'ON', 'P0P Y5P'],
  ['Elizabethtown', 'ON', 'K6T A3G'],
  ['Espanola', 'ON', 'P5E H6M'],
  ['Hamilton', 'ON', 'L8E J4E'],
  ['Manotick', 'ON', 'K4M N9P'],
  ['Carleton Place', 'ON', 'K7C B0V'],
  ['Bracebridge', 'ON', 'P1L Y9P'],
  ['Elliot Lake', 'ON', 'P5A K1T'],
  ['Penetanguishene', 'ON', 'L9M S9M'],
  ['Downtown Toronto', 'ON', 'M4W E5Y'],
  ['Caledon', 'ON', 'L7C R8P'],
  ['Pembroke', 'ON', 'K8B X0L'],
  ['Perth', 'ON', 'K7H Y1P'],
  ['Windsor', 'ON', 'N8P Y6E'],
  ['Sturgeon Falls', 'ON', 'P2B G6C'],
  ['Essex', 'ON', 'N0R C4B'],
  ['Peterborough', 'ON', 'K9K V1L'],
  ['Simcoe', 'ON', 'N3Y S3N'],
  ['Aylmer', 'ON', 'N5H T4A'],
  ['Port Perry', 'ON', 'L9L C0X'],
  ['Owen Sound', 'ON', 'N4K M7L'],
  ['Port Hope', 'ON', 'L1A R6E'],
  ['Renfrew', 'ON', 'K7V E3R'],
  ['Tecumseh', 'ON', 'N8V V1Y'],
  ['Uxbridge', 'ON', 'L9P H3E'],
  ['Amherstburg', 'ON', 'N9V K7L'],
  ['Holland Landing', 'ON', 'L9N N9X'],
  ['London', 'ON', 'N5V C2L'],
  ['Dunnville', 'ON', 'N1A G1P'],
  ['Wallaceburg', 'ON', 'N8A B2L'],
  ['Kingsville', 'ON', 'N9Y S3C'],
  ['Russell', 'ON', 'K4R X6L'],
  ['Greater Sudbury', 'ON', 'P3A G1T'],
  ['Elmira', 'ON', 'N3B L2A'],
  ['Dryden', 'ON', 'P8N S3S'],
  ['Midland', 'ON', 'L4R X0N'],
  ['Kent', 'ON', 'N0P E5P'],
  ['Fort Erie', 'ON', 'L2A P7M'],
  ['Rockland', 'ON', 'K4K L0M'],
  ['Mississauga', 'ON', 'L4T A1G'],
  ['Elgin', 'ON', 'N0L M7R'],
  ['Grimsby', 'ON', 'L3M B4L'],
  ['Huron', 'ON', 'N0G J4G'],
  ['Stittsville', 'ON', 'K2S M2X'],
  ['Kapuskasing', 'ON', 'P5N M2G'],
  ['Dundas', 'ON', 'L9H C9J'],
  ['Port Colborne', 'ON', 'L3K G8L'],
  ['Courtice', 'ON', 'L1E C9J'],
  ['Kirkland Lake', 'ON', 'P2N B1C'],
  ['Etobicoke', 'ON', 'M8V G8C'],
  ['Sioux Lookout', 'ON', 'P8T H0G'],
  ['Petawawa', 'ON', 'K8H T4V'],
  ['Goderich', 'ON', 'N7A H6C'],
  ['Port Stanley', 'ON', 'N5L L2P'],
  ['Acton', 'ON', 'L7J N3C'],
  ['Gravenhurst', 'ON', 'P1P S9H'],
  ['Middlesex', 'ON', 'N0M M6H'],
  ['Belleville', 'ON', 'K8R C7G'],
  ['Innisfil', 'ON', 'L9S K1N'],
  ['Meaford', 'ON', 'N4L L2N'],
  ['Cobourg', 'ON', 'K9A L8X'],
  ['Georgetown', 'ON', 'L7G C6L'],
  ['Tecumseh Outskirts', 'ON', 'N8N M6S'],
  ['Scarborough', 'ON', 'M1B R7K'],
  ['Gloucester', 'ON', 'K1B N3A'],
  ['Wasaga Beach', 'ON', 'L9Z X6H'],
  ['Greely', 'ON', 'K4P R2Y'],
  ['Listowel', 'ON', 'N4W H0H'],
  ['Nepean', 'ON', 'K2G M4G'],
  ['Fort Frances', 'ON', 'P9A E4A'],
  ['Paris', 'ON', 'N3L Y8E'],
  ['Trenton', 'ON', 'K8V R1P'],
  ['Stouffville', 'ON', 'L4A E3K'],
  ['Bruce Peninsula', 'ON', 'N0H J4C'],
  ['St. Mary\'s', 'ON', 'N4X R3B'],
  ['Kenora', 'ON', 'P9N N8E'],
  ['Huntsville', 'ON', 'P1H B6X'],
  ['Orillia', 'ON', 'L3V R1P'],
  ['Caledonia', 'ON', 'N3W Y8V'],
  ['Bolton', 'ON', 'L7E T9T'],
  ['Delhi', 'ON', 'N4B K8R'],
  ['Smiths Falls', 'ON', 'K7A N4H'],
  ['Parry Sound', 'ON', 'P2A V7J'],
  ['Lindsay', 'ON', 'K9V R5Y'],
  ['Maple', 'ON', 'L6A Y9J'],
  ['Collingwood', 'ON', 'L9Y N2C'],
  ['Milton', 'ON', 'L9T Y1T'],
  ['King City', 'ON', 'L7B S6L'],
  ['Kingston', 'ON', 'K7K G1E'],
  ['Concord', 'ON', 'L4K K6C'],
  ['Dufferin County', 'ON', 'L0N T8E'],
  ['Coverdale', 'NB', 'E1J K4H'],
  ['Richibucto', 'NB', 'E4W B1S'],
  ['St. George', 'NB', 'E5C E7C'],
  ['Durham Bridge', 'NB', 'E6C C3C'],
  ['Millville', 'NB', 'E6E S5B'],
  ['Petitcodiac', 'NB', 'E4Z C4A'],
  ['Saint-Quentin', 'NB', 'E8A G7L'],
  ['McAdam', 'NB', 'E6J E8M'],
  ['Beresford', 'NB', 'E8K G7N'],
  ['Blackville', 'NB', 'E9B N5K'],
  ['Red Bank', 'NB', 'E9E Y6H'],
  ['Bathurst', 'NB', 'E2A P2A'],
  ['Saint-Leonard', 'NB', 'E7E M9R'],
  ['Centreville', 'NB', 'E7K S1C'],
  ['Tracadie-Sheila', 'NB', 'E1X B8X'],
  ['Paquetville', 'NB', 'E8R H3Y'],
  ['Bath', 'NB', 'E7J J9K'],
  ['Lepreau', 'NB', 'E5J G4V'],
  ['Hillsborough', 'NB', 'E4H A5H'],
  ['Boiestown', 'NB', 'E6A A4M'],
  ['Saint-Antoine', 'NB', 'E4V N0A'],
  ['Dorchester', 'NB', 'E4K E2H'],
  ['Lamèque', 'NB', 'E8T R4N'],
  ['Brantville', 'NB', 'E9H T5A'],
  ['St. Andrews', 'NB', 'E5B E3S'],
  ['Shediac', 'NB', 'E4P E3R'],
  ['Petit-Rocher', 'NB', 'E8J M6E'],
  ['Doaktown', 'NB', 'E9C C7X'],
  ['Caraquet', 'NB', 'E1W S0E'],
  ['Shippagan', 'NB', 'E8S E3S'],
  ['Bayfield', 'NB', 'E4M G8K'],
  ['Saint-Jacques', 'NB', 'E7B J5V'],
  ['Grande-Anse', 'NB', 'E8N M9L'],
  ['Sussex', 'NB', 'E4E M2J'],
  ['Belledune', 'NB', 'E8G A1V'],
  ['Apohaqui', 'NB', 'E5P X2J'],
  ['Campbellton', 'NB', 'E3N L7J'],
  ['Debec', 'NB', 'E7N K8B'],
  ['Neguac', 'NB', 'E9G Y0B'],
  ['Baie-Sainte-Anne', 'NB', 'E9A V7X'],
  ['Plaster Rock', 'NB', 'E7G C7N'],
  ['Grand Manan Island', 'NB', 'E5G V2M'],
  ['Campobello Island', 'NB', 'E5E J8N'],
  ['Smiths Creek', 'NB', 'E4G B0K'],
  ['Burtts Corner', 'NB', 'E6L M9H'],
  ['Dalhousie', 'NB', 'E8C P5L'],
  ['Nackawic', 'NB', 'E6G X4C'],
  ['Bouctouche', 'NB', 'E4S J4B'],
  ['Cap-Pelé', 'NB', 'E4N K7E'],
  ['Saint-Basile', 'NB', 'E7C L1L'],
  ['Pennfield', 'NB', 'E5H J3R'],
  ['St. Martins', 'NB', 'E5R N3M'],
  ['Inkerman', 'NB', 'E8P C1A'],
  ['Perth-Andover', 'NB', 'E7H E1A'],
  ['Baker Brook', 'NB', 'E7A L1S'],
  ['Sackville', 'NB', 'E4L V6A'],
  ['Youngs Cove', 'NB', 'E4C L5P'],
  ['Hampton', 'NB', 'E5N S4C'],
  ['Gagetown', 'NB', 'E5M V6M'],
  ['Rogersville', 'NB', 'E4Y E8B'],
  ['Bass River', 'NB', 'E4T H7B'],
  ['Canterbury', 'NB', 'E6H S4E'],
  ['Moores Mills', 'NB', 'E5A L5A'],
  ['Kingsclear', 'NB', 'E3E H5R'],
  ['Harvey', 'NB', 'E6K S8V'],
  ['Saint-Isidore', 'NB', 'E8M P3J'],
  ['Quispamsis', 'NB', 'E2G X9X'],
  ['Woodstock', 'NB', 'E7M M7R'],
  ['Hartland', 'NB', 'E7P P7K'],
  ['Kingston', 'NB', 'E5S B3L'],
  ['Florenceville', 'NB', 'E7L V2X'],
  ['Salisbury', 'NB', 'E4J Y0H'],
  ['St-Louis-de-Kent', 'NB', 'E4X E2B'],
  ['Allardville', 'NB', 'E8L M5P'],
  ['Kedgwick', 'NB', 'E8B T9Y'],
  ['Balmoral', 'NB', 'E8E R8G'],
  ['Riverview', 'NB', 'E1B P1C'],
  ['Deer Island', 'NB', 'E5V A9H'],
  ['St. Stephen', 'NB', 'E3L B3Y'],
  ['Minto', 'NB', 'E4B L5E'],
  ['Oromocto', 'NB', 'E2V H9S'],
  ['Norton', 'NB', 'E5T P7P'],
  ['Edmundston', 'NB', 'E3V T4Y'],
  ['Cocagne', 'NB', 'E4R J0G'],
  ['Stanley',' NB','E6B X1P']
]

